stages:
  - validate
  - test

syntax_check:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.1.0
  tags: [linux, docker]
  script:
    - pip install --no-index --find-links=/pip editorconfig-checker
    - editorconfig-checker
    - find . -type f -iregex ".*\.\(c\|h\|cpp\|ino\)" -exec clang-format-6.0 -i -style=file {} \; && git diff --exit-code


cppcheck:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.1.0
  tags: [linux, docker]
  script:
    - cppcheck --std=c++11 --language=c++ --error-exitcode=1 --enable=warning,style,performance,portability src/*

compile_test:
    stage: test
    image:
        name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-arduino:0.5.0
    tags: [docker, linux]
    needs: []
    script:
        - arduino-cli update
        - arduino-cli lib install "Sensirion Core@0.5.3"
        - arduino-cli lib install "Sensirion I2C SCD4x@0.3.1"
        - arduino-cli lib install "Sensirion I2C SFA3x@0.1.0"
        - arduino-cli lib install "Sensirion I2C SVM40@0.1.0"
        - arduino-cli lib install "Sensirion I2C SEN44@0.1.0"
        - arduino-cli lib install "Sensirion I2C SHT4x@0.1.0"
        - ln -s $PWD ~/Arduino/libraries/
        - arduino-cli compile --warnings all --fqbn arduino:samd:mkrzero examples/exampleUsage
        - arduino-cli compile --warnings all --fqbn arduino:avr:mega examples/exampleUsage
        - arduino-cli compile --warnings all --fqbn arduino:avr:nano examples/exampleUsage
        - arduino-cli compile --warnings all --fqbn arduino:avr:uno examples/exampleUsage
        - arduino-cli compile --warnings all --fqbn esp32:esp32:esp32 examples/exampleUsage
        - arduino-cli compile --warnings all --fqbn esp8266:esp8266:generic examples/exampleUsage
