stages:
  - validate
  - compile

compile_pio:
  stage: compile
  image:
      name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-arduino:0.5.0
  tags: [docker, linux]
  before_script:
      - pip install -U platformio
      - cp examples/basicUsage/basicUsage.ino examples/basicUsage/basicUsage.cpp
      - cp examples/extendedUsage/extendedUsage.ino examples/extendedUsage/extendedUsage.cpp
  parallel:
    matrix:
<<<<<<< HEAD
      - env: [basicUsage, extendedUsage]
=======
      - env: [basicUsage, extendedUsage, lilygo-t-display-s3_basicUsage]
>>>>>>> 431b224 (Move private declarations to the top)
  script:
      - pio run --environment ${env}

syntax_check:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-ubuntu:22.04-1.6.0
  tags: [linux, docker]
  before_script:
        - apt update
        - apt-get install -yq clang-format-14
  script:
    - find . -type f -iregex ".*\.\(c\|h\|cpp\|ino\)" -exec clang-format-14 -i -style=file {} \; && git diff --exit-code

cppcheck:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.2.0
  tags: [linux, docker]
  script:
    - cppcheck --std=c++11 --language=c++ --error-exitcode=1 --enable=warning,style,performance,portability --suppress=unreadVariable src/*

TODO_check:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.2.0
  tags: [linux, docker]
  script:
    - '! grep -rnw --exclude=.gitlab-ci.yml --exclude-dir=.git . -e "TODO"'


compile_arduino:
    stage: compile
    image:
        name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-arduino:0.5.0
    tags: [docker, linux]
    needs: []
    before_script:
        - arduino-cli update
        - arduino-cli lib install "Sensirion Core@0.5.3"
        - arduino-cli lib install "Sensirion_UPT_Core"
        - arduino-cli lib install "Sensirion I2C SCD4x@0.3.1"
        - arduino-cli lib install "Sensirion I2C SFA3x@0.1.0"
        - arduino-cli lib install "Sensirion I2C SVM4x@0.2.0"
        - arduino-cli lib install "Sensirion I2C SEN44@0.1.0"
        - arduino-cli lib install "Sensirion I2C SHT4x@0.1.0"
        - arduino-cli lib install "Sensirion I2C SEN5X@0.3.0"
        - arduino-cli lib install "Sensirion I2C SGP41@0.1.0"
        - arduino-cli lib install "Sensirion I2C SCD30@0.1.0"
        - arduino-cli lib install "Sensirion I2C STC3X@0.1.0"
        - ln -s $PWD ~/Arduino/libraries/
    parallel:
      matrix:
        - boards: [esp32:esp32:esp32, esp8266:esp8266:generic]
          examples: [basicUsage, extendedUsage]
    script:
      - arduino-cli compile --warnings all --fqbn ${boards} examples/${examples}
