#ifndef _DRIVER_CONFIG_H_
#define _DRIVER_CONFIG_H_

// Comment out lines to remove unwanted drivers

#define INCLUDE_SCD30_DRIVER
#define INCLUDE_SCD4X_DRIVER
#define INCLUDE_SEN5X_DRIVER
#define INCLUDE_SFA3X_DRIVER
#define INCLUDE_SGP4X_DRIVER
#define INCLUDE_SHT4X_DRIVER
#define INCLUDE_STC3X_DRIVER
#define INCLUDE_SVM4X_DRIVER

#endif /* _DRIVER_CONFIG_H_ */
