name: Arduino Lib

on:
  pull_request:
    branches:
      - master

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1

  arduino-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Arduino-CI/action@stable-1.x
        env:
          EXPECT_EXAMPLES: true
