name: PlatformIO Library

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  PlatformIO-Check:
    uses: sensirion/.github/.github/workflows/upt.platformio.check.yml@main
    with:
      pio-environment-list: '["basicUsage", "advancedUsage", "hacksterExample"]'

  PlatformIO-Build:
    uses: sensirion/.github/.github/workflows/upt.platformio.build.yml@main
    needs: PlatformIO-Check
    with:
      pio-environment-list: '["basicUsage", "advancedUsage", "hacksterExample"]'

  PlatformIO-PackageAndPublish:
    name: PlatformIO - Package and Publish on Tag
    if: ${{ (github.ref_type == 'tag') || (github.ref_name == 'master') }}
    needs: PlatformIO-Build
    uses: sensirion/.github/.github/workflows/upt.platformio.publish.yml@main
    with:
      should-publish: ${{ github.ref_type == 'tag' }}
    secrets:
      pio-registry-token: ${{ secrets.PIO_MKTSW_TOKEN }}
    
