name: PlatformIO Library

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  PlatformIO-Check:
    uses: sensirion/.github/.github/workflows/upt.platformio.check.yml@main
    with:
      pio-environment-list: '["basicUsage", "advancedUsage", "hacksterExample"]'

  PlatformIO-Build:
    uses: sensirion/.github/.github/workflows/upt.platformio.build.yml@main
    needs: PlatformIO-Check
    with:
      pio-environment-list: '["basicUsage", "advancedUsage", "hacksterExample"]'

  PlatformIO-Package:
    if: ${{ (github.ref_type != 'tag') && (github.ref_name == 'master') }}
    needs: PlatformIO-Build
    uses: sensirion/.github/.github/workflows/upt.platformio.publish.yml@main
    with:
      should-publish: false

  PlatformIO-Publish:
    uses: sensirion/.github/.github/workflows/upt.platformio.publish.yml@main
    if: github.ref_type == 'tag'
    needs: PlatformIO-Build
    with:
      should-publish: true
    secrets:
      pio-registry-token: ${{ secrets.PIO_MKTSW_TOKEN }}
